### ISSUE TITLE
UndefVarError: when plotting IRF

### ISSUE THREAD

**Issue by JulienPascal** [DynareJulia/Dynare.jl#12]
Hi,

There is a small typo in the file graphics.jl:

https://github.com/DynareJulia/Dynare.jl/blob/e11f044c0d1b30c72e79b8ed7b55635585fb0b38/src/graphics.jl#L125

"exonenous_name" should be " exogenous_names" (defined line 119 just above).

This sometimes lead to error messages:

```julia
LoadError: UndefVarError: exonenous_name not defined
in expression starting at In[54]:1

Stacktrace:
 [1] plot_irfs(y::Vector{Matrix{Float64}}, model::Model, symboltable::Dict{String, DynareSymbol}, filepath::String)
   @ Dynare ~/.julia/packages/Dynare/7hgrr/src/graphics.jl:125
```

**Comment by MichelJuillard** [comment]
Thanks @JulienPascal It will be corrected in the next release.
