### ISSUE TITLE
Error when running standard stoch_simul() in Julia

### ISSUE THREAD

**Issue by sousaru** [DynareJulia/Dynare.jl#39]
Hi,

I am facing an error when requesting a stoch_simul in Julia for a standard small-dimension NK model:

  "ERROR: LoadError: MethodError: no method matching get_power_deriv(::Float64, ::Int64, ::Int64)"

[ts_nk_model_mod.txt](https://github.com/DynareJulia/Dynare.jl/files/11235027/ts_nk_model_mod.txt)
[ts_nk_model.txt](https://github.com/DynareJulia/Dynare.jl/files/11235028/ts_nk_model.txt)

The dynare code works in matlab, so I don't see a reason why it should not work in Julia.

Attached you can find the .mod and .jl files (in txt format).

Thanks for transitioning from Matlab!

**Comment by MichelJuillard** [comment]
Can you please provide us with the full log? 
What is your operating system?
Can you confirm the version of the package Dynare.jl that is installed on your computer ?

**Comment by sousaru** [comment]
Windows 64-bit operating system, x64-based processor.
Dynare v0.6.3.

Full log:

[ts_nk_model_log.txt](https://github.com/DynareJulia/Dynare.jl/files/11235463/ts_nk_model_log.txt)

**Comment by MichelJuillard** [comment]
Thanks for the report. It points to an error in the definition of `get_power_deriv()`. I will fix it in a new release tomorrow. If you are in a hurry, you can just remove the types in the function argument list.

**Comment by sousaru** [comment]
Not at all; just hoping to help on the transition.
