### ISSUE TITLE
Dynare does not precompile on linux(ubuntu) with julia version 1.6.7

### ISSUE THREAD

**Issue by ruben-poghosyan** [DynareJulia/Dynare.jl#62]
`ERROR: LoadError: please run Pkg.build("Pardiso") before loading the package
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] top-level scope
   @ ~/.julia/packages/Pardiso/rrIt7/src/Pardiso.jl:6
 [3] include
   @ ./Base.jl:384 [inlined]
 [4] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
   @ Base ./loading.jl:1235
 [5] top-level scope
   @ none:1
 [6] eval
   @ ./boot.jl:360 [inlined]
 [7] eval(x::Expr)
   @ Base.MainInclude ./client.jl:446
 [8] top-level scope
   @ none:1
`

**Comment by MichelJuillard** [comment]
From the error message, can you try to first install  Pardiso and build it then install Dynare? 
Also, consider installing Julia v1.10, Dynare will run much faster.

**Comment by ruben-poghosyan** [comment]
> From the error message, can you try to first install Pardiso and build it then install Dynare? Also, consider installing Julia v1.10, Dynare will run much faster.

Thank you for the quick reply, I have tried using Dynare with Julia v1.10 but apparently some functions did not work properly, that's why I tried using the version specified in the docs, otherwise Dynare installs on Julia v1.10, for example the same mod file works on windows but does not work on linux with the exact same environment configuration

**Comment by ruben-poghosyan** [comment]
here's the model that I am trying to run, but unfortunately it does not produce a result 
`var 

L_GDP,
GDP_GAP,
L_GDP_BAR,
G_Y_BAR

;


varexo 

E_GDP_GAP,
E_L_GDP_BAR,
E_G_Y_BAR

;


parameters 
ALPHA1, ALPHA2, G; 
ALPHA1 = 0.7;
ALPHA2 = 0.9;
G = 2.3;


model;

L_GDP = GDP_GAP + L_GDP_BAR;

GDP_GAP = ALPHA1*GDP_GAP(-1) + E_GDP_GAP;

L_GDP_BAR = L_GDP_BAR(-1) + G_Y_BAR/4 - G/4 + E_L_GDP_BAR;

G_Y_BAR = ALPHA2*G_Y_BAR(-1) + (1-ALPHA2)*G + E_G_Y_BAR;

end;



shocks;


var E_GDP_GAP; stderr 1.8;
var E_L_GDP_BAR; stderr 1.2;
var E_G_Y_BAR; stderr 0.2;

end;



steady_state_model;

L_GDP = 1; 
L_GDP_BAR = 1;
GDP_GAP = 0;
G_Y_BAR = G;

end;


// steady(nocheck);
 

stoch_simul(order=1, irf=80, nograph);


varobs L_GDP;

calib_smoother(datafile='gdp.csv', diffuse_filter);`

**Comment by MichelJuillard** [comment]
Purely backward models aren't yet supported in DynareJulia. For linear models, as it is the case here, this will be added shortly.

**Comment by MichelJuillard** [comment]
> > From the error message, can you try to first install Pardiso and build it then install Dynare? Also, consider installing Julia v1.10, Dynare will run much faster.
> 
> Thank you for the quick reply, I have tried using Dynare with Julia v1.10 but apparently some functions did not work properly(for example the same mod file works on windows but does not work on linux with the exact same environment configuration), that's why I tried using the version specified in the docs, otherwise Dynare installs on Julia v1.10,

You must mean `the same mod file works in Dynare Matlab but not in Dynare Julia` rather than Windows and Linux

**Comment by ruben-poghosyan** [comment]
> > > From the error message, can you try to first install Pardiso and build it then install Dynare? Also, consider installing Julia v1.10, Dynare will run much faster.
> > 
> > 
> > Thank you for the quick reply, I have tried using Dynare with Julia v1.10 but apparently some functions did not work properly(for example the same mod file works on windows but does not work on linux with the exact same environment configuration), that's why I tried using the version specified in the docs, otherwise Dynare installs on Julia v1.10,
> 
> You must mean `the same mod file works in Dynare Matlab but not in Dynare Julia` rather than Windows and Linux

Yes, thank you for your swift response again

**Comment by MichelJuillard** [comment]
Purely backward linear models are now supported in DynareJulia with https://github.com/DynareJulia/LinearRationalExpectations.jl/commit/9f1c5cabbbff1b1d19e01b7472c7991e86ef0177

Please update your installation with
```
using Pkg
Pkg.update()
```
