### ISSUE TITLE
Not working with Julia v 1.10

### ISSUE THREAD

**Issue by McNelis-CMML** [DynareJulia/Dynare.jl#64]
At last for Windows, do not upgrade to lastest version of Julia, as advised below.  Stay at Julia v. 1.9.
I found thisout the hard way.  Apparently Dynare uses another package called MUMPS.  MUMPS is no longer working in Julia v. 1.10 and above.  So we cannot use dynare with this version of Julia.

**Comment by MichelJuillard** [comment]
Dear Paul

Thank you for reporting the issue.
This seems to be a problem that appeared in Julia on Windows lately. See [Artifact hash mismatch with P4est_jll on Julia v1.10 · Issue #3643 · JuliaLang/Pkg.jl · GitHub](https://github.com/JuliaLang/Pkg.jl/issues/3643)

3. One workaround is to turn on the `Developer mode` in Windows
4. Another workaround is to do the following:
julia> ENV[“JULIA_PKG_IGNORE_HASHES”]=1
julia> using Pkg
julia> Pkg.add(“PARMETIS_jll”)
julia> Pkg.add(“Dynare”)
[/quote]

________________________________
From: Paul McNelis ***@***.***>
Sent: Friday, February 16, 2024 1:39:13 AM
To: DynareJulia/Dynare.jl
Cc: Subscribed
Subject: [DynareJulia/Dynare.jl] Not working with Julia v 1.10 (Issue #64)


At last for Windows, do not upgrade to lastest version of Julia, as advised below. Stay at Julia v. 1.9.
I found thisout the hard way. Apparently Dynare uses another package called MUMPS. MUMPS is no longer working in Julia v. 1.10 and above. So we cannot use dynare with this version of Julia.

**Comment by mechanicpanic** [comment]
Dear Dr. McNelis,
Thanks for your report. I have tested the issue on Windows 11 and Julia 1.10, and it appears to be the same on my machine.

If you would like to use Julia 1.10 with Dynare, I can suggest to manually downgrade MUMPS to 1.4.0 in the environment where you have Dynare installed, by running `add MUMPS@1.4.0` in pkg mode. On my system, this resolves the issue.

**Comment by MichelJuillard** [comment]
Commit [c8d2d65](https://github.com/DynareJulia/Dynare.jl/commit/c8d2d65236199cce399ded4caabc2f305380c3a8) forces Dynare to use MUMPS 1.4.0. This should solve the installation problem on Windows. If it isn't the case, please, reopen this issue.

**Comment by McNelis-CMML** [comment]
Anna, can I do this in the Jupyther notebook?  I install latest Julia and
link it with the Jupyter notebook.  There will be the option to use the
earlier or later JUlia?
Do I then use
***@***.***)

before I add in and start using dynare?
Do I need to add in using ***@***.***  and do I do this before I add in and
start using dyanre?
Paul

**Comment by McNelis-CMML** [comment]
Anna, I got this error, wth the Pkg.add

***@***.***` is not a valid package name


I am using Jupyter notebook to run the dynare mod files.  Previous
versions work well.

Paul

**Comment by McNelis-CMML** [comment]
Anna and Michel:

Thanks.

I was able to get dynare working with Julia 1.10.1,  I am using Jupyter
notebooks:
I using the following command:
using Pkg
Pkg.add(PackageSpec(name="MUMPS", version="1.4.0"))

Then I added these commands:
using Pkg
ENV["JULIA_PKG_IGNORE_HASHES"] = "1"
Pkg.add("PARMETIS_jll")
Pkg.add("Random")
Pkg.add("PATHSolver")
Pkg.add("MKL")
Pkg.add("Serialization")
Pkg.add("Pardiso")
Pkg.add("Dynare")
