### ISSUE TITLE
Use of Formatting.jl

### ISSUE THREAD

**Issue by ScottPJones** [DynareJulia/Dynare.jl#65]
It looks like `Formatting.jl` (which is not currently being maintained) is no longer needed as a dependency for this package.
I was investigating changing it to use `Format.jl` (which has fixed most all of the issues with Formatting.jl), but the one place it was being used was in `src/reporting/report.jl`, but that was removed about 2 years ago.

**Comment by MichelJuillard** [comment]
Thanks @ScottPJones  for spotting this obsolete dependency. Fixed with commit https://github.com/DynareJulia/Dynare.jl/commit/e273f2f8fec10783f1fe569e9c1e28bb70625eaf
