### ISSUE TITLE
Dynare Pkg Installation Issues 

### ISSUE THREAD

**Issue by marellanom-09** [DynareJulia/Dynare.jl#79]
Hello, good afternoon,

I am currently trying to install the Dynare package on the latest version of Julia (Current stable release: v1.10.5 (August 27, 2024)), but I always get an error in the dependencies. Below is an image of the error I get. I would appreciate it if someone could help me by giving me instructions on how to solve this problem. 

![image](https://github.com/user-attachments/assets/9cb799b5-a0d0-4efd-b7fa-61c17894974d)

**Comment by marellanom-09** [comment]
Mr. Julliard thank you very much for your response,

I have been trying to solve the problem with your suggested recommendations, but unfortunately, the issue continues. Below, I show the outputs you requested: 

3. output of `versioninfo()`:

![image](https://github.com/user-attachments/assets/cdc6b728-3992-47f0-9344-9e28a0fee30c)

4. Entire output from adding `BinaryProvider`. In this regard, I was looking for information and found that the `BinaryProvider` is a pkg that has not been updated for several years and may be incompatible with the latest version of Julia:

![image](https://github.com/user-attachments/assets/3eecb43d-b20c-47d0-bbd5-44cbe634bcd5)
![image](https://github.com/user-attachments/assets/13bbc2bb-43ed-44c4-becd-7dbfbcf25850)

5. I had no problem installing `FFMPEG`, so it seems that the problem derives from the `BinaryProvider`.

Thank you again for your attention and I will be attentive to any help you can give me.

Best regards.

**Comment by MichelJuillard** [comment]
I just released a new version that doesn't need BinaryProvider. Could you try it please?

**Comment by marellanom-09** [comment]
Mr. Juillard, 

I just tried the `Dynare` installation again and it worked without any problem. I also already ran a test model and it works perfect.

Thank you very much for your help!

**Comment by MichelJuillard** [comment]
Thanks. Excellent
